<?php

/*********************************************************************
* Extension configuration file for ext "media_upload".
*
* Generated by ext 25-07-2013 10:46 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Media Upload',
  'description' => 'Fluid widget for (mass) uploading media on the Frontend using HTML5 techniques powered by Fine Uploader - http://fineuploader.com/',
  'category' => 'fe',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.0.0-dev',
  'constraints' =>
  array (
    'depends' =>
    array (
      'media' => '',
      'typo3' => '6.2.0-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
      'metadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => '',
);
