<?php

/*********************************************************************
* Extension configuration file for ext "media_upload".
*
* Generated by ext 25-07-2013 10:46 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Media Upload',
  'description' => 'Upload Media on the Frontend',
  'category' => 'fe',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '0.1.0-dev',
  'constraints' =>
  array (
    'depends' =>
    array (
      'cms' => '',
      'extbase' => '',
      'fluid' => '',
      'media' => '3.0.0-3.99.99',
      'typo3' => '6.1.1-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
      'metadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => '',
);

?>